server:
  port: 8181
  ssl:
    key-alias: test
    key-store-type: PKCS12
    key-store: test.p12
    key-store-password: test1234
#spring:
#  security:
#    user:
#      name: admin
#      password: admin123
